import { Provider } from 'react-redux'
import { store, persistor } from '../redux/store/Store'
import { PersistGate } from 'redux-persist/integration/react'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dig In",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}> */}
          <body className={inter.className}>{children}</body>
        {/* </PersistGate>
      </Provider> */}
    </html>
  );
}
